name: flutter_mqtt_location_example
description: A new Flutter application implementing location sharing with MQTT as a communication protocol.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mqtt_client: ^5.6.2
  location: ^2.3.5
  google_maps_flutter: ^0.5.21+14

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  meta: ^1.1.8


flutter:

  uses-material-design: true
